name: Add Comment to PR

on:
  pull_request_target:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hi @${{ github.event.pull_request.user.login }}! Thank you for the contribution.
